first task

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,1 +1,20 @@
 #!/usr/bin/env bash
+# Transfer a file to your server
+
+if [ "$#" -lt 3 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+
+file_path="$1"
+server_ip="$2"
+username="$3"
+ssh_Private_key="$4"
+
+scp -o StrictHostKeyChecking=no -i "$ssh_Private_key" "$file_path" "$username@$server_ip":~/
+
+if [ $? -eq 0 ]; then
+    echo "File transfered successfully"
+else
+    echo "File transfer failed"
+fi
+fi
